### ISSUE TITLE
Using codespace: Problem communicating active modules to the server

### ISSUE THREAD

**Issue by developerasun** [remotion-dev/template-three#2] opened 2023-04-13 16:40 UTC
# Error reproduce steps 

1. tried to open in a project in a codespace

![20230414_013648](https://user-images.githubusercontent.com/83855174/231826684-f588ba76-dfd0-4e1a-a4ef-c2128ceb5694.png)

2. installed deps and ran npm start

![2](https://user-images.githubusercontent.com/83855174/231826912-b6efbea4-ad70-441f-896b-66f700cd8cc6.png)

3. error thrown in browser

![err](https://user-images.githubusercontent.com/83855174/231827018-42aa5298-4ad9-4e74-8a29-3f3355d82015.png)

Haven't tried on code editor like VS code, usedgithub only. 

- Windows 11
- Chrome browser

@JonnyBurger @ahmadrosid

**Comment by JonnyBurger** [comment] 2023-04-14 13:18
I am able to reproduce this problem, however it works locally on a real system.
This seems to be an issue on the Webpack side or from GitHub codespaces, so we can do little about it.
The likelyhood of there being a fix from our side is now, which is why I am going to close it regardless.

**Closed as completed by JonnyBurger** 2023-04-14 13:18 UTC
